version: '3.1'

services:
    node:
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
          - '3000:3000'
      volumes: 
        - .:/app/pogo-coding-challenge
    
    mongo:
      image: mongo:latest
      ports: 
        - '27017:27017'
      volumes:
          - ~/pogo-coding-challenge:/data/db